name: Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run lint:ts
    - run: npm run build
    - run: npm test
    - run: npm run build:lib
    - run: npm pack
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: Bundle
        path: ${{ github.workspace }}/dist/**/*
        if-no-files-found: error
        retention-days: 7

